"""
train_rf.py - Train the Random Forest model for the SpO2 sleep-apnea screening app.

─────────────────────────────────────────────────────────────────────────────
HOW IT WORKS
─────────────────────────────────────────────────────────────────────────────
  1. Reads night_apnea.csv and night_normal.csv (generated by mock_night.py).
  2. Calls extract_features_for_night() from backend/ml.py - the SAME function
     the live backend uses, so training and inference are guaranteed to agree.
  3. Labels every window from the apnea night as 1 (apnea) and every window
     from the normal night as 0 (normal).
  4. Shuffles and splits 80 % train / 20 % test (stratified so both classes
     appear in the test set even for small datasets).
  5. Trains a RandomForestClassifier.
  6. Prints SENSITIVITY and SPECIFICITY on the test split - never just accuracy.
     (Sensitivity = how often we catch real apnea; Specificity = how rarely we
     false-alarm on a healthy sleeper.  Both matter for a screening tool.)
  7. Saves the trained model to model/rf_model.pkl with joblib.

─────────────────────────────────────────────────────────────────────────────
BEFORE RUNNING
─────────────────────────────────────────────────────────────────────────────
  Generate the mock training files first if you haven't already:

      python mock_night.py apnea  --hours 8 --out night_apnea.csv  --seed 42
      python mock_night.py normal --hours 8 --out night_normal.csv --seed 42

  Then train:

      python train_rf.py

  Then restart the server - it will load the model automatically:

      uvicorn backend.main:app --reload

─────────────────────────────────────────────────────────────────────────────
REAL-DATA CAVEAT (read before clinical use)
─────────────────────────────────────────────────────────────────────────────
  This model is trained on MOCK DATA from mock_night.py.  Mock data captures
  the broad patterns (more frequent dips in apnea nights, quieter in normal),
  but it does NOT replicate the real signal characteristics of the MAX30102
  sensor (noise floor, motion artefacts, perfusion index variation).

  Final validation MUST wait for real overnight recordings captured by the
  ESP32 hardware (Phase F, deferred until device exists).

  Report: SENSITIVITY and SPECIFICITY on mock hold-out are shown below the
  confusion matrix.  Treat them as "does the pipeline work end-to-end?" -
  not as clinical performance numbers.
"""

import csv
import os
import sys

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import joblib

# Import the shared feature extractor from the backend.
# This guarantees training and inference use the EXACT same features (A7).
from backend.ml import extract_features_for_night


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
APNEA_CSV  = "night_apnea.csv"    # label 1 (apnea)
NORMAL_CSV = "night_normal.csv"   # label 0 (normal)
MODEL_DIR  = "model"
MODEL_PATH = os.path.join(MODEL_DIR, "rf_model.pkl")

# Random seed for reproducibility
SEED = 42

# RF hyperparameters - reasonable defaults; tune after real data exists
N_ESTIMATORS = 100
MAX_DEPTH     = None   # grow until pure leaves (fine for mock data; add limit with real data)


# ---------------------------------------------------------------------------
# CSV loader
# ---------------------------------------------------------------------------

def load_csv_as_rows(path: str) -> list:
    """
    Load a SpO2 CSV file (header t,spo2,hr,flag) into a list of dicts.
    Raises SystemExit with a helpful message if the file is missing or malformed.
    """
    if not os.path.exists(path):
        print(f"\nERROR: {path} not found.")
        print("Generate it first:")
        if "apnea" in path:
            print(f"  python mock_night.py apnea --hours 8 --out {path} --seed 42")
        else:
            print(f"  python mock_night.py normal --hours 8 --out {path} --seed 42")
        sys.exit(1)

    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames != ["t", "spo2", "hr", "flag"]:
            print(f"\nERROR: {path} has wrong header: {reader.fieldnames}")
            print("Expected: t,spo2,hr,flag")
            sys.exit(1)

        for row in reader:
            try:
                rows.append({
                    "t":    int(row["t"]),
                    "spo2": int(row["spo2"]),
                    "hr":   int(row["hr"]),
                    "flag": row["flag"].strip(),
                })
            except (ValueError, KeyError) as exc:
                print(f"WARNING: skipping malformed row in {path}: {row} ({exc})")

    print(f"  Loaded {len(rows):,} rows from {path}")
    return rows


# ---------------------------------------------------------------------------
# Training pipeline
# ---------------------------------------------------------------------------

def main():
    print("\n=== SpO2 RF Training Pipeline ===\n")

    # ── 1. Load mock CSV files ───────────────────────────────────────────────
    print("1. Loading training data...")
    apnea_rows  = load_csv_as_rows(APNEA_CSV)
    normal_rows = load_csv_as_rows(NORMAL_CSV)

    # ── 2. Extract features (same function the live backend uses) ────────────
    print("\n2. Extracting 60-second window features...")

    apnea_features  = extract_features_for_night(apnea_rows)
    normal_features = extract_features_for_night(normal_rows)

    print(f"  Apnea night:  {len(apnea_features)} valid windows")
    print(f"  Normal night: {len(normal_features)} valid windows")

    if not apnea_features or not normal_features:
        print("\nERROR: no windows extracted - check that your CSV files are long enough.")
        sys.exit(1)

    # ── 3. Build X (features) and y (labels) arrays ─────────────────────────
    # Labels: 1 = apnea window, 0 = normal window.
    X_apnea  = np.array([fv for _, fv in apnea_features])
    X_normal = np.array([fv for _, fv in normal_features])

    y_apnea  = np.ones(len(X_apnea),  dtype=int)
    y_normal = np.zeros(len(X_normal), dtype=int)

    X = np.vstack([X_apnea, X_normal])
    y = np.concatenate([y_apnea, y_normal])

    print(f"\n  Total windows: {len(X)}  (apnea: {len(X_apnea)}, normal: {len(X_normal)})")

    # ── 4. Train / test split (stratified so both classes appear in both sets) ──
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.20,
        random_state=SEED,
        stratify=y,   # ensures ~20% apnea and ~20% normal in the test set
    )
    print(f"\n3. Split: {len(X_train)} train / {len(X_test)} test (80/20, stratified)")

    # ── 5. Train the Random Forest ────────────────────────────────────────────
    print(f"\n4. Training RandomForestClassifier (n_estimators={N_ESTIMATORS})...")
    model = RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        class_weight="balanced",   # helps when apnea/normal window counts differ
        random_state=SEED,
        n_jobs=-1,                 # use all CPU cores
    )
    model.fit(X_train, y_train)
    print("   Training complete.")

    # ── 6. Evaluate on the held-out test set ─────────────────────────────────
    print("\n5. Evaluating on held-out test set...")
    y_pred = model.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)
    # Confusion matrix layout (label 0 = normal, label 1 = apnea):
    #   [[TN, FP],
    #    [FN, TP]]
    tn, fp, fn, tp = cm.ravel()

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    accuracy    = (tp + tn) / len(y_test)

    print(f"\n   Confusion matrix (rows = actual, cols = predicted):")
    print(f"               Pred normal  Pred apnea")
    print(f"   Actual normal   {tn:6d}      {fp:6d}")
    print(f"   Actual apnea    {fn:6d}      {tp:6d}")
    print(f"\n   Accuracy    : {accuracy:.3f}   (shown for reference - not the primary metric)")
    print(f"   SENSITIVITY : {sensitivity:.3f}   (fraction of real apnea windows detected)")
    print(f"   SPECIFICITY : {specificity:.3f}   (fraction of normal windows correctly not flagged)")
    print()
    print("   Sensitivity = TP / (TP + FN) - missing apnea is the dangerous failure mode.")
    print("   Specificity = TN / (TN + FP) - false alarms waste specialist appointments.")

    # ── 7. Save the model ────────────────────────────────────────────────────
    os.makedirs(MODEL_DIR, exist_ok=True)
    joblib.dump(model, MODEL_PATH)
    print(f"\n6. Model saved to {MODEL_PATH}")

    # ── 8. Feature importance (diagnostic, not functional) ───────────────────
    feature_names = [
        "spo2_min", "spo2_mean", "spo2_max", "spo2_range", "spo2_std",
        "desat_depth", "desat_count", "secs_below_thr", "hr_mean", "hr_std",
    ]
    importances = model.feature_importances_
    ranked      = sorted(zip(feature_names, importances), key=lambda x: -x[1])

    print("\n   Feature importances (most predictive first):")
    for name, imp in ranked:
        bar = "#" * int(imp * 40)   # ASCII bar - avoids Windows cp1252 encoding issues
        print(f"     {name:<25s} {imp:.3f}  {bar}")

    # ── 9. Mandatory disclaimer ────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("WARNING: Model trained on MOCK DATA ONLY.")
    print("Mock patterns are simplified and do not match real MAX30102 signal")
    print("characteristics.  Real-data validation is REQUIRED before any")
    print("clinical use.  Deferred to when hardware is available (Phase F).")
    print("=" * 60 + "\n")

    print("Next step: restart the server to load the model:")
    print("  uvicorn backend.main:app --reload\n")


if __name__ == "__main__":
    main()
